// ─── TENANTS ────────────────────────────────────────────────────
// These are the companies that subscribe to SiteFlow.
// In production this comes from Supabase. For now it's local state.

export const TENANTS = [
  {
    id: 'T001',
    company: 'OpenServe Contractors SA',
    contactName: 'Peloa Gaeri',
    contactEmail: 'peloa@openserve-c.co.za',
    contactPhone: '082 111 2233',
    industry: 'fibre_rollout',
    tier: 'pro',
    status: 'active',
    joinedDate: '2025-01-15',
    billingStatus: 'paid',
    nextBillingDate: '2025-05-15',
    monthlyRate: 2500,
    projects: 1,
    zones: 12,
    users: 18,
    subcontractors: 15,
    lastActive: '2025-04-20',
    notes: 'First paying client. Soweto fibre rollout Phase 1.',
  },
  {
    id: 'T002',
    company: 'Mthembu Road Works',
    contactName: 'Lungelo Mthembu',
    contactEmail: 'lungelo@mthemburoads.co.za',
    contactPhone: '071 234 5566',
    industry: 'road_construction',
    tier: 'demo',
    status: 'active',
    joinedDate: '2025-03-02',
    billingStatus: 'demo',
    nextBillingDate: null,
    monthlyRate: 0,
    projects: 1,
    zones: 4,
    users: 3,
    subcontractors: 4,
    lastActive: '2025-04-18',
    notes: 'Evaluating Pro tier. Follow up end of April.',
  },
  {
    id: 'T003',
    company: 'Dube Paving & Civil',
    contactName: 'Sibusiso Dube',
    contactEmail: 'sibusiso@dubepaving.co.za',
    contactPhone: '073 445 6677',
    industry: 'paving',
    tier: 'pro',
    status: 'active',
    joinedDate: '2025-02-20',
    billingStatus: 'overdue',
    nextBillingDate: '2025-04-20',
    monthlyRate: 2500,
    projects: 2,
    zones: 8,
    users: 9,
    subcontractors: 6,
    lastActive: '2025-04-15',
    notes: 'Invoice outstanding. Send reminder.',
  },
  {
    id: 'T004',
    company: 'Zulu Municipal Services',
    contactName: 'Nomvula Zulu',
    contactEmail: 'nomvula@zulumunic.gov.za',
    contactPhone: '031 789 0011',
    industry: 'municipal',
    tier: 'tailored',
    status: 'active',
    joinedDate: '2025-01-28',
    billingStatus: 'paid',
    nextBillingDate: '2025-05-28',
    monthlyRate: 8500,
    projects: 4,
    zones: 32,
    users: 41,
    subcontractors: 22,
    lastActive: '2025-04-21',
    notes: 'Largest client. Custom SLA in place.',
  },
  {
    id: 'T005',
    company: 'Khumalo Trenching Co',
    contactName: 'Thabo Khumalo',
    contactEmail: 'thabo@khumalot.co.za',
    contactPhone: '064 321 0099',
    industry: 'trenching',
    tier: 'demo',
    status: 'suspended',
    joinedDate: '2025-03-10',
    billingStatus: 'demo',
    nextBillingDate: null,
    monthlyRate: 0,
    projects: 0,
    zones: 0,
    users: 1,
    subcontractors: 0,
    lastActive: '2025-03-15',
    notes: 'Signed up but went quiet. Account suspended after 30 days.',
  },
];

export const TIER_CONFIG = {
  demo:     { label: 'Demo',     color: '#888',    bg: '#f0ede6', monthly: 0 },
  pro:      { label: 'Pro',      color: '#1a5fa0', bg: '#deeaf6', monthly: 2500 },
  tailored: { label: 'Tailored', color: '#534ab7', bg: '#eeedfe', monthly: null },
};

export const STATUS_CONFIG = {
  active:    { label: 'Active',    badge: 'badge-green' },
  suspended: { label: 'Suspended', badge: 'badge-red'   },
  cancelled: { label: 'Cancelled', badge: 'badge-gray'  },
};

export const BILLING_CONFIG = {
  paid:    { label: '✓ Paid',    badge: 'badge-green' },
  overdue: { label: '! Overdue', badge: 'badge-red'   },
  demo:    { label: 'Demo',      badge: 'badge-gray'  },
  pending: { label: 'Pending',   badge: 'badge-amber' },
};

export const INDUSTRY_LABELS = {
  fibre_rollout:    'Fibre Rollout',
  road_construction:'Road Construction',
  paving:           'Paving',
  plumbing:         'Plumbing',
  municipal:        'Municipal',
  utility:          'Utility',
  trenching:        'Trenching',
  other:            'Other',
};
